services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: Sistema_Empresarial
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: isaac2004
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./Backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: dev 
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/Sistema_Empresarial 
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: isaac2004

  frontend:
    build: ./Frontend
    ports:
      - "3000:3000"
    command: npm run dev -- --host
    depends_on:
      - backend

volumes:
  postgres_data: